Build Deck Use Case Basic Implementations
ThomasKeough/bedrock pull request #10
Opened 2023-11-13 21:54 UTC by stanleypangg

2023-11-14 19:42 UTC, ThomasKeough requested changes
concerned about some CA specifics – i think the cards need to be passed to the interactor in the input data object. see my comments and lmk what u think

2023-11-14 19:42 UTC, ThomasKeough commented on src/use_cases/build_deck/BuildDeckInputData.java
i think the input data should pass the cards that will become part of the deck to the interactor. then, the interactor will build the deck. this means that the deck doesn't need to be included in the input data, but the 6 cards should be.
^^ this design makes more sense to me but your plan might work better. lmk what u think

2023-11-14 19:42 UTC, ThomasKeough commented on src/use_cases/build_deck/BuildDeckInteractor.java
this is where the cards should be passed to the deck initializer

2023-11-14 19:54 UTC, stanleypangg commented
> concerned about some CA specifics – i think the cards need to be passed to the interactor in the input data object. see my comments and lmk what u think

o true, im looking at week5git and realized i did the CA wrong, thanks for your input, i'll change it!

2023-11-20 01:44 UTC, ThomasKeough approved these changes
changes look great

2023-11-20 01:44 UTC, merged