Build Card and Build Deck Use Cases
ThomasKeough/bedrock pull request #7
Opened 2023-11-11 17:23 UTC by stanleypangg

2023-11-11 20:36 UTC, ThomasKeough commented on src/entities/CommonCollection.java
might be helpful to add an "atLimit" method that returns false if the number of cards in <cards> is less than the limit, and true otherwise.

2023-11-11 20:39 UTC, ThomasKeough commented on src/interface_adapters/add_to_collection/AddToCollectionState.java
in setCard: might want to set on a copy of the card, to be consistent with the initializer

2023-11-11 20:41 UTC, ThomasKeough requested changes
overall good work. just a couple minor additions/changes that i think would be helpful. see the comments and lmk what you think.

2023-11-11 20:48 UTC, stanleypangg commented
> @stanleypangg overall good work. just a couple minor additions/changes that i think would be helpful. see the comments and lmk what you think.

sounds good! ill work and commit those changes

2023-11-12 20:02 UTC, ThomasKeough approved these changes
changes are good. would have to make Card implement Cloneable to use .copy() so we decided to not do that, unless we deem it necessary later on.

2023-11-12 20:02 UTC, merged